// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	models "actions_google/pkg/domain/models"

	mock "github.com/stretchr/testify/mock"
)

// ActionsBrokerRepository is an autogenerated mock type for the ActionsBrokerRepository type
type ActionsBrokerRepository struct {
	mock.Mock
}

// SendAction provides a mock function with given fields: newAction
func (_m *ActionsBrokerRepository) SendAction(newAction *models.RequestGoogleAction) bool {
	ret := _m.Called(newAction)

	if len(ret) == 0 {
		panic("no return value specified for SendAction")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*models.RequestGoogleAction) bool); ok {
		r0 = rf(newAction)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewActionsBrokerRepository creates a new instance of ActionsBrokerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActionsBrokerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActionsBrokerRepository {
	mock := &ActionsBrokerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
